volumeclassname: volstorage
volumepvname: pv
volumepvpath: /nfsdata/olap/
volumeserver: 172.31.15.33
volumepvspace: 1Gi
volumename: www-web  # 不能随意修改
volumenum:
- num: "0"
- num: "1"
- num: "2"
# 总结点数，最后一个节点索引，如：4个节点，最后一个索引是3
lastnodeindex: 2
image: registry.elensdata.com/elensai/olap2kylin:v3

mysqlimage: registry.elensdata.com/elensai/mysql:5.7
mysqlvolumepvpath: /nfsdata/olap/mysql
mysqlrootpasswd: 123456
mysqlvolumespace: 1Gi

olapimage: registry.elensdata.com/elensai/olap2:v1