apiVersion: v1
kind: Service
metadata:
  name: java-svc
  labels:
    dep: java-svc
spec:
  type: NodePort
  ports:
    - name: java-8300
      port: 8300
      targetPort: java-port
      nodePort: 8300
      protocol: TCP
  selector:
    app: java-pod
