apiVersion: v1
kind: Service
metadata:
  name: zhiwen-app-svc
  labels:
    dep: zhiwen-svc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.SERVICE_PORT }}
      targetPort: {{ .Values.SERVICE_PORT }}
      nodePort: {{ .Values.SERVICE_PORT }}
      protocol: TCP
  selector:
    app: zhiwen-pod
