apiVersion: v1
kind: Service
metadata:
  name: zw-rabbitmq-svc
  labels:
    dep: zw-rabbitmq-svc
spec:
  type: NodePort
  ports:
    - name: rabbitmq-5672
      port: 5672
      targetPort: rabbitmq-port
      nodePort: {{ .Values.RABBITMQ_PORT }}
      protocol: TCP
    - name: rabbitmq-15672
      port: 15672
      targetPort: rabbitmq-web
      nodePort: {{ .Values.RABBITMQ_WEB_PORT }}
      protocol: TCP
  selector:
    app: zw-rabbitmq-pod
