apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zw-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zw-rabbitmq-pod
    spec:
      containers:
        - name: zw-rabbitmq-c
          image: "registry.elensdata.com/elensai/rabbitmq:3.7.14-management"
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.RABBITMQ_DEFAULT_USER }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.RABBITMQ_DEFAULT_PASS }}
          ports:
            - name: rabbitmq-port
              containerPort: 5672
              protocol: TCP
            - name: rabbitmq-web
              containerPort: 15672
              protocol: TCP
      #     volumeMounts:
      #     - mountPath: '/var/lib/rabbitmq'
      #       name: rabbitmydb 
      # volumes:
      #   - name: rabbitmydb
      #     persistentVolumeClaim:
      #       claimName: zw-rabbitmq-claim
      
