apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    dep: web-svc
spec:
  type: NodePort
  ports:
    - port: 8370
      targetPort: 8370
      nodePort: {{ .Values.WEB_PORT }}
      protocol: TCP
  selector:
    app: web-pod
