apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env-config
  namespace: {{ .Values.APP_NAME}}
data:
  config: |-
    // APM 拆分
    // var BASE_URL = 'http://{{ .Values.DO_MAIN}}:{{.Values.SERVICE_PORT}}';
    var BASE_URL = "";
    var APM_CONFIG = {
      alias: 'apm-zhiwen-web-search', // 当前子模块别称
      messageOrigin: '*', // apm壳子部署域名
      padding: [0, 0, 0, 0], // apm壳子中iframe的偏移量 上 右 下 左 单位 px
    };
    var HIDE_BAR = false;
    // 测试
    var DEFAULTRECOID= {{ .Values.DEFAULTRECOID}};
    var DEFAULTIDCARDFRONT= {{ .Values.DEFAULTIDCARDFRONT}};
    var DEFAULTIDCARDBACK= {{ .Values.DEFAULTIDCARDBACK}};
    var QUOTAINVOCE= {{ .Values.QUOTAINVOCE}};
    var LICENSEPLATE= {{ .Values.LICENSEPLATE}};
    var VATINVIOCE= {{ .Values.VATINVIOCE}};
    var VEHICLEFRONT= {{ .Values.VEHICLEFRONT}};
    var VEHICLEBACK= {{ .Values.VEHICLEBACK}};
    var DRIVING= {{ .Values.DRIVING}};
    var BANKCARD= {{ .Values.BANKCARD}};
    var BUSSINESS= {{ .Values.BUSSINESS}};
    var RECEIPT= {{ .Values.RECEIPT}};
    sessionStorage.setItem("DEFAULTRECOID", DEFAULTRECOID);
    window.BASE_URL = BASE_URL;
    window.APM_CONFIG = APM_CONFIG;
    window.HIDE_BAR = HIDE_BAR;
