apiVersion: v1
kind: ConfigMap
metadata:
  name: slaves
  namespace: elens-olap
data:
  slaves-config: |-
    {{- range .Values.volumenum}}
    web-{{ .num }}.ha-svc.elens-olap.svc.cluster.local
    {{- end }}