apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: blacklist
data:
  esconfig: |-
    # es.hostName=192.168.1.87
    # es.hostName=118.190.58.150
    es.hostName=172.31.15.38
    #es.hostName=10.9.72.21
    es.schema=http
    es.port=9200
    es.log.index=blacklist_saas
    es.log.type=log
    es.data.index=blacklist_single_new
    es.data.type=data

    ngix_ip=192.168.1.241:8080
    solr_return_num=100

    Person=1
    Entity=2
    Vessel=3
    Aircraft=4
    PEP=5
    Other=6
    1=Person
    2=Entity
    3=Vessel
    4=Aircraft
    5=PEP
    6=Other

    stopwords=AKTSIONERNOE OBSHCHESTVO,OPEN JOINT-STOCK COMPANY,Obshchestvo s ogranichennoy otvetstvennostyu,GROUP co. LTD,OTKRYTOE AKTSIONERNOE OBSHCHESTVO,LIMITED LIABILITY COMPANY,JOINT-STOCK COMPANY,GROUP COMPANY Limited,GROUP COMPANY LTD

    initPassword=1234elensdata

    azkabanZipPath=/data/tomcat8/webapps/ftp_batch_screening.zip