apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgre-vol
  nfs:
    path: /nfsdata/blacklist
    server: 172.31.15.36

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgre-vol
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: applogs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: applogs-vol
  nfs:
    path: /nfsdata/blacklist_logs
    server: 172.31.15.36

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: applogs-vol
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

